version: "3"

services:
  ray-head:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6379:6379 # redis
      - 8265:8265 # dashboard
      - 10001:10001 #head-node
      - 8005:8005 #serve
    env_file:
      - .env
    command: "ray start --head  --dashboard-host=0.0.0.0 --block && serve deploy ray-config.yaml" ##  serve run ray_multiplexing:app
    volumes:
      - ./focoos:/app/focoos
      - ./apps:/app/apps
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    networks:
      - ray_net
  ray-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ray-head
    env_file:
      - .env
    command: "ray start --address=ray-head:6379 --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 2
      resources:
        reservations:
         devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]

    networks:
      - ray_net

networks:
  ray_net:
    driver: bridge
