proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8005
grpc_options:
  port: 9000
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: DEBUG
  logs_dir: null
  enable_access_log: true

applications:
- name: multi-model
  route_prefix: /
  import_path: ray-serve:app
  runtime_env: {"pip": ["requests", "Pillow~=10.4.0",
  "supervision~=0.24.0", "pydantic~=2.8.2",
  "pydantic-settings~=2.5.0", "tqdm~=4.66.6", "numpy~=1.26.4", "scipy~=1.14.1","gradio","opencv-python==4.9.0.80"],
  "env_vars": {"NUM_MODELS_PER_REPLICA": "25"}
  }
  deployments:
  - name: multi-model
    num_replicas: 1
    ray_actor_options:
      num_cpus: 4
      num_gpus: 1
