layers_prunable_fai_cls_n_coco = [
    "model.backbone.features.2.conv_list.0.conv",
    "model.backbone.features.2.conv_list.1.conv",
    "model.backbone.features.2.conv_list.2.conv",
    "model.backbone.features.2.conv_list.3.conv",
    "model.backbone.features.3.conv_list.0.conv",
    "model.backbone.features.3.conv_list.1.conv",
    "model.backbone.features.3.conv_list.2.conv",
    "model.backbone.features.3.conv_list.3.conv",
    "model.backbone.features.4.conv_list.0.conv",
    "model.backbone.features.4.conv_list.1.conv",
    "model.backbone.features.4.conv_list.2.conv",
    "model.backbone.features.4.conv_list.3.conv",
    # "model.backbone.features.5.conv_list.0.conv",
    # "model.backbone.features.5.conv_list.1.conv",
    # "model.backbone.features.5.conv_list.2.conv",
    # "model.backbone.features.5.conv_list.3.conv",
    # "model.backbone.features.6.conv_list.0.conv",
    # "model.backbone.features.6.conv_list.1.conv",
    # "model.backbone.features.6.conv_list.2.conv",
    # "model.backbone.features.6.conv_list.3.conv",
    # "model.backbone.features.6.conv_list.3.conv",
    # "model.backbone.features.7.conv_list.0.conv",
    # "model.backbone.features.7.conv_list.1.conv",
    # "model.backbone.features.7.conv_list.2.conv",
    # "model.backbone.features.7.conv_list.3.conv",
]

layers_prunable_fai_cls_s_coco = [
    "model.backbone.features.2.conv_list.0.conv",
    "model.backbone.features.2.conv_list.1.conv",
    "model.backbone.features.2.conv_list.2.conv",
    "model.backbone.features.2.conv_list.3.conv",
    "model.backbone.features.3.conv_list.0.conv",
    "model.backbone.features.3.conv_list.1.conv",
    "model.backbone.features.3.conv_list.2.conv",
    "model.backbone.features.3.conv_list.3.conv",
    "model.backbone.features.4.conv_list.0.conv",
    "model.backbone.features.4.conv_list.1.conv",
    "model.backbone.features.4.conv_list.2.conv",
    "model.backbone.features.4.conv_list.3.conv",
    # "model.backbone.features.5.conv_list.0.conv",
    # "model.backbone.features.5.conv_list.1.conv",
    # "model.backbone.features.5.conv_list.2.conv",
    # "model.backbone.features.5.conv_list.3.conv",
    # "model.backbone.features.6.conv_list.0.conv",
    # "model.backbone.features.6.conv_list.1.conv",
    # "model.backbone.features.6.conv_list.2.conv",
    # "model.backbone.features.6.conv_list.3.conv",
    # "model.backbone.features.7.conv_list.0.conv",
    # "model.backbone.features.7.conv_list.1.conv",
    # "model.backbone.features.7.conv_list.2.conv",
    # "model.backbone.features.7.conv_list.3.conv",
]

layers_prunable_fai_cls_m_coco = [
    "model.backbone.features.2.conv_list.0.conv",
    "model.backbone.features.2.conv_list.1.conv",
    "model.backbone.features.2.conv_list.2.conv",
    "model.backbone.features.2.conv_list.3.conv",
    "model.backbone.features.3.conv_list.0.conv",
    "model.backbone.features.3.conv_list.1.conv",
    "model.backbone.features.3.conv_list.2.conv",
    "model.backbone.features.3.conv_list.3.conv",
    "model.backbone.features.4.conv_list.0.conv",
    "model.backbone.features.4.conv_list.1.conv",
    "model.backbone.features.4.conv_list.2.conv",
    "model.backbone.features.4.conv_list.3.conv",
    # "model.backbone.features.5.conv_list.0.conv",
    # "model.backbone.features.5.conv_list.1.conv",
    # "model.backbone.features.5.conv_list.2.conv",
    # "model.backbone.features.5.conv_list.3.conv",
    # "model.backbone.features.6.conv_list.0.conv",
    # "model.backbone.features.6.conv_list.1.conv",
    # "model.backbone.features.6.conv_list.2.conv",
    # "model.backbone.features.6.conv_list.3.conv",
    # "model.backbone.features.7.conv_list.0.conv",
    # "model.backbone.features.7.conv_list.1.conv",
    # "model.backbone.features.7.conv_list.2.conv",
    # "model.backbone.features.7.conv_list.3.conv",
]
